### ISSUE TITLE
On pharo-dev, Esteban suggested an better readable version of Seaside.st

### ISSUE THREAD

**Issue by StephanEggermont** [Geal/pharo-seaside-docker-example#1]
Gofer it 
    url: ‘filetree:///home/deploy’;
    package: ‘WebCounter’;
    package: ‘HelloWorldApp’;
    load.
stdout << 'WebCounter installed'; lf.
ZnZincServerAdaptor startOn: 8080.
WAAdmin register: WebCounter asApplicationAt: 'webcounter’.

**Comment by Geal** [comment]
Great, thanks! Fixed in 2f41d9d

**Comment by StephanEggermont** [comment]
It looks like there are some quote issues (open+close quotes instead of straight ones). I'm afraid I copied from a place that did the substitution

**Comment by Geal** [comment]
It should be alright now
